### ISSUE TITLE
Limit commands to those specified in the app

### ISSUE THREAD

**Issue by lordmundi** [timmo001/system-bridge#353]
# Description
Opening a system up to run any command sent over the API could be dangerous. One option that users may appreciate is a way to whitelist individual commands that are allowed with all others being rejected.

## Suggested Actions
Add a configuration setting to let users specify a whitelist of commands that should be allowed to be executed through the API.

**Comment by timmo001** [comment]
I do like this idea. Opening up the entire system could be pretty dangerous. This could also allow the use of aliases for commands.

This will require:

- [ ] Storage solution for commands (electron settings solution or a DB solution)
- [ ] GUI for configuring commands (Settings)
- [ ] Refactor of command endpoint to handle aliases instead of raw commands

**Comment by lordmundi** [comment]
although i don't know if you need a GUI.  The config could be as simple as
a text file with the list of allowed commands one per line... or in JSON or
something. Just trying to think of things that might make an initial
version a little easier to get going.
