### ISSUE TITLE
High CPU load when checking new data

### ISSUE THREAD

**Issue by spitz66** [timmo001/system-bridge#705]
### Description

First of all, thanks for your great work however I have an issue as follows:

Is it expected that CPU Load goes to 100% during checking of new data?
I have default Observer Interval set to 30000 ms and it corresponds well with CPU Load, then back to normal:

![SB_2](https://user-images.githubusercontent.com/65921206/129365351-e56d1a34-41b9-4aff-8bdc-c9fbf1f78c00.JPG)

![SB_3](https://user-images.githubusercontent.com/65921206/129365626-80556862-8e57-4c53-815d-fcb5b03171b5.JPG)

### What Platform / OS are you running?

Windows

### What version are you running?

19043.1110

**Comment by timmo001** [comment]
Does the CPU go straight back down afterwards? (You also have windows defender scanning so it might be throwing things off)

I'm thinking we may want to split these intervals so the observer checks for changes for each endpoint independently instead of running all checks at once.

I've not seen a spike show up in the data frontend however:

![image](https://user-images.githubusercontent.com/28114703/129379776-5b4e6bd2-f089-48e7-b885-c00b8ca3ff9a.png)

This may work differently though
